// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouuzkeyotnujojkavjcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91dXprZXlvdG51am9qa2F2amNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDI0NzksImV4cCI6MjA2NjYxODQ3OX0.mepMKZpI8N6AItLVhyGEpPANbTZ9Yaqhte_kE92x2vA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);